name: Pandoc Transformation

on:
  push:
  #pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
          cache: 'pip' # caching pip dependencies
      - name: print versions for debugging
        run: |
          whoami
          python --version
          pip --version
          sed --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install -r ./pdf_to_odt_docx/requirements.txt
          python -m pip install -r ./sphinx-config/requirements.txt
          # python -m pip install . # install local script
      - name: transform pdf to docx / odt
        run: |
          python3 ./pdf_to_odt_docx/converter.py -in ./input -out ./intermediate
      - name: Archive intermediate folder
        uses: actions/upload-artifact@v4
        with:
          name: intermediate
          path: |
            ./intermediate/
        # Use always() to always run this step to publish test results when there are test failures
      - name: run pandoc
        uses: docker://pandoc/core:3.5
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --columns=100
            --list-tables=true
            --extract-media ./output
            --output=./output/Automotive-SPICE-PAM-v40.rst
            ./intermediate/Automotive-SPICE-PAM-v40.pdf.word.docx
      - name: run pandoc native
        uses: docker://pandoc/core:3.5
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --write=native
            --output=./output/Automotive-SPICE-PAM-v40.native
            ./intermediate/Automotive-SPICE-PAM-v40.pdf.word.docx
      - name: run sed 2
        run:
          seq 8 | sed '$!N;s/^\(2\)\n\(.*\)/\0\n\1/;P;D'
      - name: run sed
        run: #--regexp-extended
          sed -e '/^4\.[0-9]\{1,2\}\.[0-9]\. \([A-Za-z]\{3\}.[0-9]\) \(.*\)$/i before' ./output/Automotive-SPICE-PAM-v40.rst > ./output/Automotive-SPICE-PAM-v40.rst.sed
          #sed --regexp-extended -e '/^4\.[0-9]{1,2}\.[0-9]\. ([A-Za-z]{3}.[0-9]) (.*)/{{a .. need \2\n   id \1; i before}}' ./output/Automotive-SPICE-PAM-v40.rst > ./output/Automotive-SPICE-PAM-v40.rst.sed
      - name: Archive output folder
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            ./output/
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Setup github pages
        id: pages
        uses: actions/configure-pages@v5
      - name: copy content from output to sphinx-content folder
        run: |
          cp ./output/Automotive-SPICE-PAM-v40.rst ./sphinx-content/ASPICE.rst
          mkdir -p ./sphinx-content/output
          cp -r ./output/media ./sphinx-content/output
      - name: Archive sphinx-content folder
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-content
          path: |
            ./sphinx-content/
      - name: Render the documentation with the transformed rst files
        run: >
          sphinx-build
          -c ./sphinx-config
          -b html ./sphinx-content ./public
          # -vv
          # --jobs=auto
          # --show-traceback
          --keep-going
          # --fail-on-warning
      - name: Upload artifact to github pages
        uses: actions/upload-pages-artifact@v3
        with:
         path: ./public

  # github pages deployment job
  github_pages_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: convert_via_pandoc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
