name: Pandoc Transformation

on:
  push:
  #pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
          cache: 'pip' # caching pip dependencies
      - name: print versions for debugging
        run: python --version ; pip --version ; whoami
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install -r ./pdf_to_odt_docx/requirements.txt
          python -m pip install -r ./sphinx-config/requirements.txt
          # python -m pip install . # install local script
      - name: transform pdf to docx / odt
        run: |
          python3 ./pdf_to_odt_docx/converter.py -in ./input -out ./intermediate
      - name: Archive intermediate folder
        uses: actions/upload-artifact@v4
        with:
          name: intermediate
          path: |
            ./intermediate/
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: run pandoc I
        uses: docker://pandoc/core:3.4
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --list-tables=true
            --columns=100
            --extract-media ./output
            --output=./output/Automotive-SPICE-PAM-v40.pdf.word.docx.rst
            ./intermediate/Automotive-SPICE-PAM-v40.pdf.word.docx
      - name: Replace values in rst files
        run: |
          sed --version
          sed -e "/^ *:header-rows: 1$/d" -e "s/ +$//g" ./output/Automotive-SPICE-PAM-v40.pdf.word.docx.rst > ./output/Automotive-SPICE-PAM-v40.pdf.word.docx.rst.sed.rst
          sed -E -e "s/( +- )([^ ])/\1 \2/g" ./output/Automotive-SPICE-PAM-v40.pdf.word.docx.rst > ./output/Automotive-SPICE-PAM-v40.pdf.word.docx.rst.final_sed.rst
      - name: run pandoc II
        uses: docker://pandoc/core:3.4
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --list-tables=true
            --columns=100
            --output=./output/Automotive-SPICE-PAM-v40.pdf.docx.rst
            ./intermediate/Automotive-SPICE-PAM-v40.pdf.docx
      - name: Archive output folder
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            ./output/
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Setup github pages
        id: pages
        uses: actions/configure-pages@v5
      - name: copy content from output to sphinx-content folder
        run: |
          cp ./output/Automotive-SPICE-PAM-v40.pdf.word.docx.rst.final_sed.rst ./sphinx-content/ASPICE.rst
      - name: Render the documentation with the transformed rst files
        run: >
          sphinx-build
          -c ./sphinx-config
          -b html ./sphinx-content ./public
          # -vv
          # --jobs=auto
          # --show-traceback
          --keep-going
          # --fail-on-warning
      - name: Upload artifact to github pages
        uses: actions/upload-pages-artifact@v3
        with:
         path: ./public

  # github pages deployment job
  github_pages_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: convert_via_pandoc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4